name: Test pull request

on:
  pull_request:
    branches: [ master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./...